project:
  type: website

website:
  title: "SEM in HCI Research using SEMinR"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - instructors.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: source

