project:
  type: website
bibliography: bibliography.bib
website:
  title: "SEM in HCI Research using SEMinR"
  
#  sidebar:
#    contents: auto
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: whyseminr.html
        text: Why SEM?
      - href: coursedetails.html
        text: Details
      - text: Course instructors
        menu:
          - andre.qmd
          - lilian.qmd
          - nicholas.qmd
          - soumya.qmd
  repo-url: https://github.com/sem-in-r/chi2023-course-site
  repo-actions: [edit, issue]
#  twitter-card: true

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: source

